In [81]:
import pandas as pd
import geopandas as gpd
import rasterio
# osx | tk
%matplotlib tk

In [23]:
%matplotlib --list

Available matplotlib backends: ['agg', 'auto', 'cairo', 'gtk3', 'gtk3agg', 'gtk3cairo', 'gtk4', 'gtk4agg', 'gtk4cairo', 'inline', 'macosx', 'module://matplotlib_inline.backend_inline', 'nbagg', 'notebook', 'osx', 'pdf', 'pgf', 'ps', 'qt', 'qt5', 'qt5agg', 'qt5cairo', 'qt6', 'qtagg', 'qtcairo', 'svg', 'template', 'tk', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wx', 'wxagg', 'wxcairo']

In [82]:
ls ~/Documents/GDrive/JBB/Reporte_2025/Artropofauna/Shape/"Mapa de calor.gpkg"

'/home/nelson/Documents/GDrive/JBB/Reporte_2025/Artropofauna/Shape/Mapa de calor.gpkg'

In [83]:
fname = '/home/nelson/Documents/GDrive/JBB/Reporte_2025/Artropofauna/Shape/Mapa de calor.gpkg'

In [84]:
with rasterio.open(fname) as gpkg:
	if gpkg.subdatasets:
		for raster in gpkg.subdatasets:
			with rasterio.open(raster) as src:
				print(src.profile)
				
	else:  # Just one raster
		print(gpkg.profile)

RasterioIOError: '/home/nelson/Documents/GDrive/JBB/Reporte_2025/Artropofauna/Shape/Mapa de calor.gpkg' not recognized as being in a supported file format.

In [32]:
gpd.list_layers(fname)

          name geometry_type
0       blocks       Point Z
1       points       Point Z
2        lines  LineString Z
3    polylines  LineString Z
4        texts       Point Z
5      hatches     Polygon Z
6      inserts       Point Z
7      drawing          None
8      headers          None
9    linetypes          None
10      layers          None
11   dimstyles          None
12  textstyles          None
13     appdata          None

In [73]:
lay = gpd.read_file(fname, layer='polylines')
lay.describe()

,handle,block,etype,space,ocolor,color24,transparency,lweight,linewidth,ltscale,visible,width,thickness
count,21.000000,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,2.100000e+01,21.0
mean,150.571429,-1.0,18.0,0.0,256.0,2302755.0,0.0,-1.0,0.0,1.0,1.0,2.335620e-03,0.0
std,11.977360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.887813e-19,0.0
min,131.000000,-1.0,18.0,0.0,256.0,2302755.0,0.0,-1.0,0.0,1.0,1.0,2.335620e-03,0.0
25%,141.000000,-1.0,18.0,0.0,256.0,2302755.0,0.0,-1.0,0.0,1.0,1.0,2.335620e-03,0.0
50%,151.000000,-1.0,18.0,0.0,256.0,2302755.0,0.0,-1.0,0.0,1.0,1.0,2.335620e-03,0.0
75%,160.000000,-1.0,18.0,0.0,256.0,2302755.0,0.0,-1.0,0.0,1.0,1.0,2.335620e-03,0.0
max,170.000000,-1.0,18.0,0.0,256.0,2302755.0,0.0,-1.0,0.0,1.0,1.0,2.335620e-03,0.0

In [64]:
lay.iloc[0]

handle                                                        132
block                                                          -1
etype                                                          13
space                                                           0
layer                                                        Loca
olinetype                                                 BYLAYER
linetype
color                                             243,166,178,255
ocolor                                                        256
color24                                                  15967922
transparency                                             33554432
lweight                                                        -1
linewidth                                                     0.0
ltscale                                                       1.0
visible                                                         1
thickness                                                     0.0
ext                                                     (3:0,0,1)
name                                                        SOLID
solid                                                           1
associative                                                     0
hstyle                                                          0
hpattern                                                        1
doubleflag                                                      0
angle                                                         0.0
scale                                                         0.0
deflines                                                        0
geometry        POLYGON Z ((-74.13075446299996 4.5933533470000...
Name: 0, dtype: object

In [74]:
lay.iloc[0]

handle                                                        131
block                                                          -1
etype                                                          18
space                                                           0
layer                                                        Loca
olinetype                                              CONTINUOUS
linetype
color                                                35,35,35,255
ocolor                                                        256
color24                                                   2302755
transparency                                                    0
lweight                                                        -1
linewidth                                                     0.0
ltscale                                                       1.0
visible                                                         1
width                                                    0.002336
thickness                                                     0.0
ext                                                   (3:0,0,0.1)
geometry        LINESTRING Z (-74.13075446299996 4.59335334700...
Name: 0, dtype: object

In [67]:
lay.plot()