In [24]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
#import rasterio
# osx | tk
%matplotlib tk

In [2]:
%matplotlib --list

Available matplotlib backends: ['agg', 'auto', 'cairo', 'gtk3', 'gtk3agg', 'gtk3cairo', 'gtk4', 'gtk4agg', 'gtk4cairo', 'inline', 'macosx', 'nbagg', 'notebook', 'osx', 'pdf', 'pgf', 'ps', 'qt', 'qt5', 'qt5agg', 'qt5cairo', 'qt6', 'qtagg', 'qtcairo', 'svg', 'template', 'tk', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wx', 'wxagg', 'wxcairo']

In [2]:
ls ~/Documents/GDrive/JBB/Reporte_2025/Artropofauna/'Anexo 8 Datos Darwin Core Consolidados.xlsx'

'/home/nelson/Documents/GDrive/JBB/Reporte_2025/Artropofauna/Anexo 8 Datos Darwin Core Consolidados.xlsx'

In [3]:
fname = '/home/nelson/Documents/GDrive/JBB/Reporte_2025/Artropofauna/Anexo 8 Datos Darwin Core Consolidados.xlsx'

In [4]:
artr = pd.read_excel(fname)

In [6]:
print(artr.iloc[0].to_string())

gbifID                                                                        3902035418
accessRights                                                                         NaN
bibliographicCitation                                                                NaN
language                                                                             NaN
license                                                                     CC_BY_NC_4_0
modified                                                            2022-08-19T00:49:47Z
publisher                                                                iNaturalist.org
references                             https://www.inaturalist.org/observations/69470815
rightsHolder                                                             Loreta Rosselli
type                                                                                 NaN
institutionID                                                                        NaN
collectionID                                                                         NaN
datasetID                                                                            NaN
institutionCode                                                              iNaturalist
collectionCode                                                              Observations
datasetName                                      iNaturalist research-grade observations
ownerInstitutionCode                                                                 NaN
basisOfRecord                                                          HUMAN_OBSERVATION
informationWithheld                    Coordinate uncertainty increased to 31394m at ...
dataGeneralizations                                                                  NaN
dynamicProperties                                                                    NaN
occurrenceID                           https://www.inaturalist.org/observations/69470815
catalogNumber                                                                   69470815
recordNumber                                                                         NaN
recordedBy                                                               Loreta Rosselli
recordedByID                                                                         NaN
individualCount                                                                      NaN
organismQuantity                                                                     NaN
organismQuantityType                                                                 NaN
sex                                                                        Indeterminate
lifeStage                                                                          Adult
reproductiveCondition                                                                NaN
caste                                                                                NaN
behavior                                                                             NaN
vitality                                                                            dead
establishmentMeans                                                                   NaN
degreeOfEstablishment                                                                NaN
pathway                                                                              NaN
georeferenceVerificationStatus                                                       NaN
occurrenceStatus                                                                 PRESENT
preparations                                                                         NaN
disposition                                                                          NaN
associatedOccurrences                                                                NaN
associatedReferences                                                                 NaN
associatedSequences                                                                  NaN
associatedTaxa                                                                       NaN
otherCatalogNumbers                                                                  NaN
occurrenceRemarks                      A 50cm de quebrada en matorral nativo, se encu...
organismID                                                                           NaN
organismName                                                                         NaN
organismScope                                                                        NaN
associatedOrganisms                                                                  NaN
previousIdentifications                                                              NaN
organismRemarks                                                                      NaN
materialEntityID                                                                     NaN
materialEntityRemarks                                                                NaN
verbatimLabel                                                                        NaN
materialSampleID                                                                     NaN
eventID                                                                              NaN
parentEventID                                                                        NaN
eventType                                                                            NaN
fieldNumber                                                                          NaN
eventDate                                                                            NaT
eventTime                                                                 15:52:33-05:00
startDayOfYear                                                                      43.0
endDayOfYear                                                                        43.0
year                                                                              2021.0
month                                                                                2.0
day                                                                                 12.0
verbatimEventDate                              Fri Feb 12 2021 15:52:33 GMT-0500 (GMT-5)
habitat                                                                              NaN
samplingProtocol                                                                     NaN
sampleSizeValue                                                                      NaN
sampleSizeUnit                                                                       NaN
samplingEffort                                                                       NaN
fieldNotes                                                                           NaN
eventRemarks                                                                         NaN
locationID                                                                           NaN
higherGeographyID                                                                    NaN
higherGeography                                                                      NaN
continent                                                                  SOUTH_AMERICA
waterBody                                                                            NaN
islandGroup                                                                          NaN
island                                                                               NaN
countryCode                                                                           CO
stateProvince                                                               Cundinamarca
county                                                                               NaN
municipality                                                                         NaN
locality                                                                             NaN
verbatimLocality                                                        Cundinamarca, CO
verbatimElevation                                                                    NaN
verticalDatum                                                                        NaN
verbatimDepth                                                                        NaN
minimumDistanceAboveSurfaceInMeters                                                  NaN
maximumDistanceAboveSurfaceInMeters                                                  NaN
locationAccordingTo                                                                  NaN
locationRemarks                                                                      NaN
decimalLatitude                                                                 4.805294
decimalLongitude                                                                   -74.0
coordinateUncertaintyInMeters                                                    31394.0
coordinatePrecision                                                                  NaN
pointRadiusSpatialFit                                                                NaN
verbatimCoordinateSystem                                                             NaN
verbatimSRS                                                                          NaN
footprintWKT                                                                         NaN
footprintSRS                                                                         NaN
footprintSpatialFit                                                                  NaN
georeferencedBy                                                                      NaN
georeferencedDate                                                                    NaN
georeferenceProtocol                                                                 NaN
georeferenceSources                                                                  NaN
georeferenceRemarks                                                                  NaN
geologicalContextID                                                                  NaN
earliestEonOrLowestEonothem                                                          NaN
latestEonOrHighestEonothem                                                           NaN
earliestEraOrLowestErathem                                                           NaN
latestEraOrHighestErathem                                                            NaN
earliestPeriodOrLowestSystem                                                         NaN
latestPeriodOrHighestSystem                                                          NaN
earliestEpochOrLowestSeries                                                          NaN
latestEpochOrHighestSeries                                                           NaN
earliestAgeOrLowestStage                                                             NaN
latestAgeOrHighestStage                                                              NaN
lowestBiostratigraphicZone                                                           NaN
highestBiostratigraphicZone                                                          NaN
lithostratigraphicTerms                                                              NaN
group                                                                                NaN
formation                                                                            NaN
member                                                                               NaN
bed                                                                                  NaN
identificationID                                                               154592116
verbatimIdentification                                                               NaN
identificationQualifier                                                              NaN
typeStatus                                                                           NaN
identifiedBy                                                             Loreta Rosselli
identifiedByID                                                                       NaN
dateIdentified                                                       2021-02-12T20:54:23
identificationReferences                                                             NaN
identificationVerificationStatus                                                     NaN
identificationRemarks                                                                NaN
taxonID                                                                           106862
scientificNameID                                                                     NaN
acceptedNameUsageID                                                              5791370
parentNameUsageID                                                                    NaN
originalNameUsageID                                                                  NaN
nameAccordingToID                                                                    NaN
namePublishedInID                                                                    NaN
taxonConceptID                                                                       NaN
scientificName                             Neostrengeria macropa (H.Milne Edwards, 1853)
acceptedNameUsage                                                                    NaN
parentNameUsage                                                                      NaN
originalNameUsage                                                                    NaN
nameAccordingTo                                                                      NaN
namePublishedIn                                                                      NaN
namePublishedInYear                                                                  NaN
higherClassification                                                                 NaN
kingdom                                                                         Animalia
phylum                                                                        Arthropoda
class                                                                       Malacostraca
order                                                                           Decapoda
superfamily                                                                          NaN
family                                                                Pseudothelphusidae
subfamily                                                                            NaN
tribe                                                                                NaN
subtribe                                                                             NaN
genus                                                                      Neostrengeria
genericName                                                                Neostrengeria
subgenus                                                                             NaN
infragenericEpithet                                                                  NaN
specificEpithet                                                                  macropa
infraspecificEpithet                                                                 NaN
cultivarEpithet                                                                      NaN
taxonRank                                                                        SPECIES
verbatimTaxonRank                                                                    NaN
vernacularName                                                                       NaN
nomenclaturalCode                                                                    NaN
taxonomicStatus                                                                 ACCEPTED
nomenclaturalStatus                                                                  NaN
taxonRemarks                                                                         NaN
datasetKey                                          50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingCountry                                                                     CO
lastInterpreted                                               2025-04-29 21:21:34.354000
elevation                                                                            NaN
elevationAccuracy                                                                    NaN
depth                                                                                NaN
depthAccuracy                                                                        NaN
distanceFromCentroidInMeters                                                         NaN
issue                                  COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...
mediaType                                                                     StillImage
hasCoordinate                                                                        1.0
hasGeospatialIssues                                                                  0.0
taxonKey                                                                       5791370.0
acceptedTaxonKey                                                               5791370.0
kingdomKey                                                                           1.0
phylumKey                                                                           54.0
classKey                                                                           229.0
orderKey                                                                           637.0
familyKey                                                                      3254116.0
genusKey                                                                       4645244.0
subgenusKey                                                                          NaN
speciesKey                                                                     5791370.0
species                                                            Neostrengeria macropa
acceptedScientificName                     Neostrengeria macropa (H.Milne Edwards, 1853)
verbatimScientificName                                             Neostrengeria macropa
typifiedName                                                                         NaN
protocol                                                                     DWC_ARCHIVE
lastParsed                                                    2025-04-29 21:21:34.354000
lastCrawled                                                   2025-04-29 09:11:01.700000
repatriated                                                                          0.0
relativeOrganismQuantity                                                             NaN
projectId                              https://www.inaturalist.org/projects/crabs-of-...
isSequenced                                                                          0.0
gbifRegion                                                                 LATIN_AMERICA
publishedByGbifRegion                                                      LATIN_AMERICA
level0Gid                                                                            COL
level0Name                                                                      Colombia
level1Gid                                                                        COL.5_2
level1Name                                                                   Bogotá D.C.
level2Gid                                                                      COL.5.1_2
level2Name                                                                   Bogotá D.C.
level3Gid                                                                            NaN
level3Name                                                                           NaN
iucnRedListCategory                                                                   LC

In [5]:
artr.groupby('taxonomicStatus', dropna=False).size()

taxonomicStatus
ACCEPTED    27198
DOUBTFUL      134
SYNONYM       642
NaN          1582
dtype: int64

In [6]:
artr.groupby('taxonRank', dropna=False).size()

taxonRank
CLASS           262
FAMILY        10881
FORM              6
GENUS          3160
ORDER          2218
PHYLUM           38
SPECIES       12580
SUBSPECIES      311
UNRANKED        100
dtype: int64

In [7]:
artr.loc[
	(artr.decimalLatitude == '4,761111 -74,103611'),
	['decimalLatitude', 'decimalLongitude']] = [4.761111, -74.103611]

In [8]:
artr['decimalLatitude'] = artr.decimalLatitude.astype(float)
artr['decimalLongitude'] = artr.decimalLongitude.astype(float)

In [9]:
artr.loc[artr.decimalLongitude > -70, ['decimalLatitude', 'decimalLongitude']]

       decimalLatitude  decimalLongitude
29474              4.0            6032.0

In [10]:
artr[['decimalLatitude', 'decimalLongitude']].describe()

       decimalLatitude  decimalLongitude
count     29555.000000      29555.000000
mean          4.654846        -73.885819
std           0.101330         35.517980
min           3.742986        -74.663400
25%           4.610147        -74.111532
50%           4.664600        -74.083300
75%           4.704767        -74.063861
max           4.855570       6032.000000

In [11]:
dat = artr.loc[
	(artr.taxonomicStatus == 'ACCEPTED') &
	(artr.taxonRank == 'SPECIES') & 
	(artr.decimalLongitude < -70 ),
	['scientificName', 'decimalLongitude', 'decimalLatitude']
]

In [12]:
gdat = gpd.GeoDataFrame(
	dat, 
	geometry=gpd.points_from_xy(dat.decimalLongitude, dat.decimalLatitude),
	crs=4326
)

In [13]:
gdat.plot()

In [30]:
locs = gpd.read_file("shared/loca/Loca.shp")
locs = locs.to_crs(4326)

In [31]:
greg = gdat.sjoin(locs, how='left', predicate='within')

In [32]:
locs = locs.merge(
	greg.groupby(['LocNombre', 'scientificName']
		).size(
		).reset_index(
		).groupby('LocNombre'
		).size(
		).reset_index(
		).rename(columns={0: 'Riqueza'}),
	how='left',
	on='LocNombre'
)

In [33]:
locs['Localidad'] = locs.LocNombre.str.title()

In [34]:
locs.to_file("chapters/artropofauna/dat/riqueza_localidad.shp")

In [46]:
locs = gpd.read_file("chapters/artropofauna/dat/riqueza_localidad.shp")
fig, ax = plt.subplots(figsize=(32, 16))
locs.plot(
	ax=ax, 
	column="Riqueza", 
	legend=True, 
	cmap='summer', 
	#legend_kwds={'loc': 'upper left'}
)
#plt.show()
plt.savefig("test.png", dpi=300, bbox_inches='tight', format='png')